/*
 * This file is part of CPLib.
 *
 * CPLib is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * CPLib is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with CPLib. If
 * not, see <https://www.gnu.org/licenses/>.
 */

#ifndef CPLIB_RANDOM_HPP_
#define CPLIB_RANDOM_HPP_

#include <concepts>
#include <cstdint>
#include <initializer_list>
#include <iterator>
#include <random>
#include <ranges>
#include <string>
#include <vector>

namespace cplib {

// Concept to check if a type behaves like a map for weighted choice.
// It must be a range, and its elements must have a 'second' member we can use as a weight.
template <typename T>
concept MapLike = std::ranges::range<T> && requires(const std::ranges::range_value_t<T>& value) {
  typename T::mapped_type;
  { value.second } -> std::convertible_to<const typename T::mapped_type&>;
};

/**
 * Random number generator that provides various methods to generate random numbers and perform
 * random operations.
 */
struct Random {
 public:
  using Engine = std::mt19937_64;

  /**
   * Construct a random generator with default seed.
   */
  explicit Random();

  /**
   * Construct a random generator with given seed.
   *
   * @param seed The seed of the random generator.
   */
  explicit Random(std::uint64_t seed);

  /**
   * Construct a random generator with seed which generated command-line arguments.
   *
   * @param args The command-line arguments.
   */
  explicit Random(const std::vector<std::string>& args);

  /**
   * Reseed the generator with a new seed.
   *
   * @param seed The new seed value.
   */
  auto reseed(std::uint64_t seed) -> void;

  /**
   * Reseed the generator with a seed generated by `argc` and `argv`.
   *
   * @param args The command-line arguments.
   */
  auto reseed(const std::vector<std::string>& args) -> void;

  /**
   * Get the engine used by the random generator.
   *
   * @return A reference to the engine.
   */
  auto engine() -> Engine&;

  /**
   * Generate a random integer in the range [from, to].
   *
   * @tparam T The type of the integer.
   * @param from The lower bound of the range.
   * @param to The upper bound of the range.
   * @return The randomly generated integer.
   */
  template <std::integral T>
  auto next(T from, T to) -> T;

  /**
   * Generate a random floating-point number in the range [from, to].
   *
   * @tparam T The type of the floating-point number.
   * @param from The lower bound of the range.
   * @param to The upper bound of the range.
   * @return The randomly generated floating-point number.
   */
  template <std::floating_point T>
  auto next(T from, T to) -> T;

  /**
   * Generate a random boolean value with 50% probability of being true.
   *
   * @return The randomly generated boolean value.
   */
  auto next_bool() -> bool;

  /**
   * Generate a random boolean value with a given probability of being true.
   *
   * @param true_prob The probability of the boolean being true.
   * @return The randomly generated boolean value.
   */
  auto next_bool(double true_prob) -> bool;

  /**
   * Generate a weighted random number in the range [from, to] with specified weighting type.
   *
   * @tparam T The type of the number (must be integral or floating-point).
   * @param from The lower bound of the range.
   * @param to The upper bound of the range.
   * @param type The weighting type. Positive values prefer higher numbers, negative values prefer
   * lower numbers.
   * @return The weighted random number.
   */
  template <typename T>
    requires std::integral<T> || std::floating_point<T>
  auto wnext(T from, T to, int type) -> T;

  /**
   * Return a random value from the given initializer_list.
   *
   * @tparam T The type of the value.
   * @param init_list The initializer_list to choose from.
   * @return A random value from the initializer_list.
   */
  template <class T>
  auto choice(std::initializer_list<T> init_list) -> T;

  /**
   * Return a random iterator from the given range.
   *
   * @tparam It The type of the iterator.
   * @param first The beginning of the range.
   * @param last The end of the range.
   * @return A random iterator from the range.
   */
  template <std::forward_iterator It>
  auto choice(It first, It last) -> It;

  /**
   * Return a random iterator from the given container.
   *
   * @tparam Container The type of the container.
   * @param container The container to choose from.
   * @return A random iterator from the container.
   */
  template <std::ranges::forward_range Container>
  auto choice(Container& container);

  /**
   * Return a random iterator from the given map container by utilizing the values of the map
   * container as weights for weighted random number generation.
   *
   * @tparam Map The type of the map container.
   * @param map The map container to choose from.
   * @return A random iterator from the map container.
   */
  template <MapLike Map>
  auto weighted_choice(const Map& map);

  /**
   * Shuffle the elements in the given range.
   *
   * @tparam RandomIt The type of the random access iterator.
   * @param first The beginning of the range.
   * @param last The end of the range.
   */
  template <std::random_access_iterator RandomIt>
  auto shuffle(RandomIt first, RandomIt last) -> void;

  /**
   * Shuffle the elements in the given container.
   *
   * @tparam Container The type of the container.
   * @param container The container to shuffle.
   */
  template <std::ranges::random_access_range Container>
  auto shuffle(Container& container) -> void;

 private:
  Engine engine_;
};
}  // namespace cplib

#include "random.i.hpp"  // IWYU pragma: export

#endif
