name: Run test
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "LICENSE"
      - "README.md"
jobs:
  run-test:
    strategy:
      matrix:
        include:
          - c_compiler: "gcc-13"
            cxx_compiler: "g++-13"
          - c_compiler: "gcc-14"
            cxx_compiler: "g++-14"
          - c_compiler: "clang-16"
            cxx_compiler: "clang++-16"
          - c_compiler: "clang-17"
            cxx_compiler: "clang++-17"
          - c_compiler: "clang-18"
            cxx_compiler: "clang++-18"
    name: Test ${{ matrix.cxx_compiler }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}

      - name: Build project
        run: cmake --build build --parallel

      - name: Run tests with CTest
        run: ctest --test-dir build --output-on-failure --parallel

  sanitizer-test:
    name: Test clang++-18 ASan UBSan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B build-sanitizer \
            -DCMAKE_C_COMPILER=clang-18 \
            -DCMAKE_CXX_COMPILER=clang++-18 \
            -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined"

      - name: Build project
        run: cmake --build build-sanitizer --parallel

      - name: Run tests with CTest
        run: ctest --test-dir build-sanitizer --output-on-failure --parallel
